slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # SLAM mode
    mode: "mapping"         # mapowanie na bieżąco
    # mode: "localization"  # w trybie pracy na gotowej mapie

    # map parameters
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05

    # pose graph
    loop_closure_enabled: true
    loop_closure_frequency: 1.0
    transform_timeout: 0.2

    # sensor noise tuning
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
    scan_topic: "scan"

    # queue_size: 50
